/* eslint-disable quotes */
export const CONSTANTS = {
  INITIAL_KEYWORDS : [
    "Breaking News",
    "World News",
    "Politics",
    "Business",
    "Technology",
    "Science",
    "Health",
    "Entertainment",
    "Sports",
    "Environment",
    "Economy",
    "Education",
    "Lifestyle",
    "Travel",
    "Opinion",
    "Analysis",
    "Finance",
    "Culture",
    "Weather",
    "Crime",
    "Fashion",
    "Food",
    "Art",
    "Music",
    "Film",
    "Books",
    "History",
    "Religion",
    "Fashion",
    "Celebrity",
    "Gaming",
    "Pets",
    "Automobile",
    "Space",
    "Astronomy",
    "Psychology",
    "Technology Trends",
    "Startups",
    "Innovation",
    "Fashion Trends",
    "Design",
    "Architecture",
    "Nature",
    "Wildlife",
    "Social Media",
    "Travel Destinations",
    "Cooking",
    "Fitness",
    "Mental Health",
    "Wellness",
    "DIY",
    "Parenting",
    "Relationships",
    "Human Rights",
    "Equality",
    "Diversity",
    "Fashion",
    "Sustainability",
    "Climate Change",
    "Conservation",
    "Renewable Energy",
    "Green Living",
    "Adventure",
    "Exploration",
    "Discoveries",
    "Mythology",
    "Folklore",
    "Urban Legends",
    "Supernatural",
    "Paranormal",
    "Conspiracy Theories"
  ],
  AUTHORS:[
    "Humaira Sims",
    "Santiago Solis",
    "Dawid Floyd",
    "Mateo Barlow",
    "Samia Navarro",
    "Kaden Fields",
    "Genevieve Watkins",
    "Mariah Hickman",
    "Rocco Richardson",
    "Harris Glenn"
  ],
  SOURCES: [
    "wired",
    "the-verge",
    "bbc-news",
    "business-insider",
    "time",
    "the-next-web",
    "abc-news",
    "new-scientist",
    "The Guardian",
    "The New York Times",
  ]
}
